spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 123456
      #      #Oracle
      #      driver-class-name: oracle.jdbc.OracleDriver
      #      url: jdbc:oracle:thin:@192.168.10.10:1521:xe
      #      username: renren_security
      #      password: 123456
      #      #SQLServer
      #      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
      #      username: sa
      #      password: 123456
      #      #postgresql
      #      driver-class-name: org.postgresql.Driver
      #      url: jdbc:postgresql://192.168.10.10:5432/postgres
      #      username: postgres
      #      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

##多数据源的配置，需要引用renren-dynamic-datasource
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://123456:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://123456:5432/renren_security
#      username: postgres
#      password: 123456

# Minio配置
minio:
  # minio配置的地址，端口9000
  url: http://192.168.159.135:9000
  # 账号
  accessKey: minio
  # 密码
  secretKey: minio123
  # MinIO桶名字
  bucketName: images

